/* 
 * Limepay API
 *
 * Initial build 2022-07-23
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://selectsystems.com.au
 */

using System.Runtime.Serialization;

namespace LimepayApi.Net.Exceptions
{
    [DataContract]
    public class LimepayApiError
    {
        [DataMember(Name = "status", EmitDefaultValue = false, IsRequired = false)]
        public string Status { get; set; }

        [DataMember(Name = "message", EmitDefaultValue = false, IsRequired = false)]
        public string Message { get; set; }

        [DataMember(Name = "error", EmitDefaultValue = false, IsRequired = false)]
        public LimepayApiErrorDetails Error { get; set; }
    }
}
