/* 
 * Limepay API
 *
 * Initial build 2022-07-23
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://selectsystems.com.au
 */

using System;

namespace LimepayApi.Net.Exceptions
{
    public class LimepayApiException : Exception
    {
        public LimepayApiException(string message) : base(message) {}
    }
}
