/* 
 * Limepay API
 *
 * Initial build 2022-07-23
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://selectsystems.com.au
 */

using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace LimepayApi.Net.Models
{
    /// <summary>
    /// CreateCaptureRequest
    /// </summary>
    [DataContract]
    public partial class CreateCaptureRequest :  IEquatable<CreateCaptureRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCaptureRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateCaptureRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCaptureRequest" /> class.
        /// </summary>
        /// <param name="Id">Id (required).</param>/// 
        /// <param name="Amount">Amount can be less than or equal to the previously authorised amount (required).</param>
        public CreateCaptureRequest(Int64? CaptureAmount = default(Int64?))
        {
            this.CaptureAmount = CaptureAmount;
        }


        /// <summary>
        /// Amount can be less than or equal to the previously authorised amount
        /// </summary>
        /// <value>Amount can be less than or equal to the previously authorised amount</value>
        [DataMember(Name= "captureAmount", EmitDefaultValue=false)]
        public Int64? CaptureAmount { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateCaptureRequest {\n");
            sb.Append("  CaptureAmount: ").Append(CaptureAmount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CreateCaptureRequest);
        }

        /// <summary>
        /// Returns true if CreateCaptureRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateCaptureRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateCaptureRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return
                (
                    this.CaptureAmount == other.CaptureAmount ||
                    this.CaptureAmount.Equals(other.CaptureAmount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.CaptureAmount != null)
                    hash = hash * 59 + this.CaptureAmount.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            // CaptureAmount (Int64?) minimum
            if (this.CaptureAmount < (decimal?)0)
            {
                yield return new ValidationResult("Invalid value for Amount, must be a value greater than or equal to 0.", new [] { "Amount" });
            }

            yield break;
        }
    }

}
