/* 
 * Limepay API
 *
 * Initial build 2022-07-23
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://selectsystems.com.au
 */

using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace LimepayApi.Net.Models
{
    /// <summary>
    /// CreateRefundRequest
    /// </summary>
    [DataContract]
    public partial class CreateRefundRequest :  IEquatable<CreateRefundRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateRefundRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateRefundRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateRefundRequest" /> class.
        /// </summary>
        /// <param name="Amount">The amount to refund, can be less than or equal to the previously captured amount (required).</param>
        /// <param name="TransactionId">Merchant Refund Reference.</param>
        public CreateRefundRequest(string TransactionId = default(string), Money RefundAmount = default(Money))
        {
            this.TransactionId = TransactionId;
            this.RefundAmount = RefundAmount;
        }

        /// <summary>
        /// The id relating to the original charge that is to be refunded
        /// </summary>
        /// <value>The id relating to the original charge that is to be refunded</value>
        [DataMember(Name = "transactionId", EmitDefaultValue = false)]
        public string TransactionId { get; set; }

        /// <summary>
        /// The amount to refund, can be less than or equal to the previously captured amount
        /// </summary>
        /// <value>The amount to refund, can be less than or equal to the previously captured amount</value>
        [DataMember(Name = "refundAmount", EmitDefaultValue = false)]
        public Money RefundAmount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateRefundRequest {\n");
            sb.Append("  TransactionId: ").Append(TransactionId).Append("\n");
            sb.Append("  RefundAmount: ").Append(RefundAmount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CreateRefundRequest);
        }

        /// <summary>
        /// Returns true if CreateRefundRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateRefundRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateRefundRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return
                (
                    this.TransactionId == other.TransactionId ||
                    this.TransactionId != null &&
                    this.TransactionId.Equals(other.TransactionId)
                ) &&
                (
                    this.RefundAmount == other.RefundAmount ||
                    this.RefundAmount.Equals(other.RefundAmount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.TransactionId != null)
                    hash = hash * 59 + this.TransactionId.GetHashCode();
                    hash = hash * 59 + this.RefundAmount.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            // Amount (decimal?) minimum
            if(this.RefundAmount.Amount < 0)
            {
                yield return new ValidationResult("Invalid value for RefundAmount, must be a value greater than or equal to 0.", new [] { "Amount" });
            }

            yield break;
        }
    }

}
