/* 
 * Limepay API
 *
 * Initial build 2022-07-23
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://selectsystems.com.au
 */

using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace LimepayApi.Net.Models
{

    /// <summary>
    /// The PaymentActionResponse object
    /// </summary>
    [DataContract]
    public partial class PaymentActionResponse :  IEquatable<PaymentActionResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentActionResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PaymentActionResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentActionResponse" /> class.
        /// </summary>
        /// <param name="ThreeDSAuthorisationId">ThreeDSAuthorisationId</param>
        /// <param name="RedirectURL">The redirect Url</param>
        public PaymentActionResponse(string PaymentToken = default(string), PaymentActionRequired PaymentActionRequired = default(PaymentActionRequired))
        {
            this.PaymentToken = PaymentToken;
            this.PaymentActionRequired = PaymentActionRequired;
        }

        /// <summary>
        /// Gets or Sets ThreeDSAuthorisationId
        /// </summary>
        [DataMember(Name= "paymentToken", EmitDefaultValue=false)]
        public string PaymentToken { get; set; }

        /// <summary>
        /// Gets or Sets RedirectURL
        /// </summary>
        [DataMember(Name= "paymentActionRequired", EmitDefaultValue=false)]
        public PaymentActionRequired PaymentActionRequired { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Money {\n");
            sb.Append("  PaymentToken: ").Append(PaymentToken).Append("\n");
            sb.Append("  PaymentActionRequired: ").Append(PaymentActionRequired).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PaymentActionResponse);
        }

        /// <summary>
        /// Returns true if AccessToken instances are equal
        /// </summary>
        /// <param name="other">Instance of AccessToken to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentActionResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.PaymentToken == other.PaymentToken ||
                    this.PaymentToken.Equals(other.PaymentToken)
                ) && 
                (
                    this.PaymentActionRequired == other.PaymentActionRequired ||
                    this.PaymentActionRequired.Equals(other.PaymentActionRequired)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)

                if (this.PaymentToken != null)
                    hash = hash * 59 + this.PaymentToken.GetHashCode();
                hash = hash * 59 + this.PaymentActionRequired.GetHashCode();

                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
