/* 
 * Limepay API
 *
 * Initial build 2022-07-23
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://selectsystems.com.au
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace LimepayApi.Net.Model.Types
{
    /// <summary>
    /// The type of transaction
    /// </summary>
    /// <value>The type of transaction (online, manual, instore)</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TypeEnum
    {
        /// <summary>
        /// Enum for Type
        /// </summary>
        [EnumMember(Value = "online")]
        Online,
        [EnumMember(Value = "manual")]
        Manual,
        [EnumMember(Value = "instore")]
        Instore,
    }

    /// <summary>
    /// The type of Status
    /// </summary>
    /// <value>The type of status (created, paid, cancelled, fulfilled, returned)</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum StatusEnum
    {
        /// <summary>
        /// Enum for Status
        /// </summary>
        [EnumMember(Value = "created")]
        Created,
        [EnumMember(Value = "paid")]
        Paid,
        [EnumMember(Value = "cancelled")]
        Cancelled,
        [EnumMember(Value = "fulfilled")]
        Fulfilled,
        [EnumMember(Value = "returned")]
        Returned
    }

    /// <summary>
    /// The type of currency
    /// </summary>
    /// <value>The type of currency (AUD, NZD)</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CurrencyEnum
    {
        /// <summary>
        /// Enum for currency
        /// </summary>
        [EnumMember(Value = "AUD")]
        AUD,
        [EnumMember(Value = "NZD")]
        NZD
    }
}